version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:14.0.2
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt -y install xvfb
      - run: xvfb-run mvn package

workflows:
  build:
    jobs:
      - build


