version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.0
    steps:
      - checkout
      - run: |
          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ubuntu-restricted-extras ttf-mscorefonts-installer
      - run: mvn package

workflows:
  build:
    jobs:
      - build


