version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:14.0.2
    steps:
      - run: |
          sudo apt-get update
          sudo apt -y install xvfb
      - run: xvfb `mvn package`

workflows:
  build:
    jobs:
      - build


